### ISSUE TITLE
WIP: Switch from erlang_protobuffs to gpb [JIRA: RIAK-2892]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak#878]
Dependencies:
- [ ] basho/riak_kv#1501
- [ ] basho/riak_api#114
- [ ] basho/riak_pb#197

**Comment by Basho-JIRA** [comment]
PR:

https://github.com/basho/riak_ee/pull/411 

***[posted via JIRA by Luke Bakken]***
